package com.exploreros.glass.ble;

import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.bluetooth.BluetoothGatt;
import android.bluetooth.BluetoothGattCallback;
import android.bluetooth.BluetoothGattCharacteristic;
import android.bluetooth.BluetoothGattDescriptor;
import android.bluetooth.BluetoothGattService;
import android.content.Context;
import com.exploreros.glass.ancs.AncsConsumer;
import com.exploreros.glass.ancs.AncsNotifications;
import com.exploreros.glass.ams.AmsState;
import com.exploreros.glass.ams.AmsRemote;
import com.exploreros.glass.core.LineAccumulator;
import com.exploreros.glass.core.Heartbeat;
import com.exploreros.glass.core.PhoneActions;
import com.exploreros.glass.core.LinkSession;
import com.exploreros.glass.core.ProtocolException;
import com.exploreros.glass.core.ProtocolMessage;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/** API19 central. Initial scan only discovers; caller explicitly selects address. */
public final class ExplorerBleClient {
    public static final UUID SERVICE = UUID.fromString("D973F2E0-B19E-11EE-A506-0242AC120002"), RX = UUID.fromString("D973F2E1-B19E-11EE-A506-0242AC120002"), TX = UUID.fromString("D973F2E2-B19E-11EE-A506-0242AC120002"), CCCD = UUID.fromString("00002902-0000-1000-8000-00805F9B34FB");
    public interface Callbacks { void status(String text); void candidate(String name, String address); void received(ProtocolMessage message); void capabilities(boolean ancs, boolean ams); void notification(AncsNotifications.Notification value); void removed(long uid); void invalidated(long uid); void media(AmsState.Snapshot value); void cleared(); void notificationsCleared(); void disconnected(); void authenticated(); }
    private static final UUID GATT_SERVICE = UUID.fromString("00001801-0000-1000-8000-00805F9B34FB"), SERVICE_CHANGED = UUID.fromString("00002A05-0000-1000-8000-00805F9B34FB");
    private final android.os.Handler main = new android.os.Handler(android.os.Looper.getMainLooper());
    private final Context context; private final byte[] key; private final Callbacks callbacks; private final BluetoothAdapter adapter; private final List<String> candidates = new ArrayList<String>(); private BluetoothGatt gatt; private BluetoothGattCharacteristic rx, tx; private GattOperationQueue queue; private LinkSession session; private final LineAccumulator lines = new LineAccumulator(); private boolean capsSent, ancsReady, amsReady, authenticatedReported, peerPhoneActions; private AncsConsumer ancs; private AmsRemote ams;
    public ExplorerBleClient(Context context, byte[] key, Callbacks callbacks) { this.context = context.getApplicationContext(); this.key = key.clone(); this.callbacks = callbacks; this.adapter = BluetoothAdapter.getDefaultAdapter(); }
    public boolean reconnectSaved(String address) { if (address == null || adapter == null || !adapter.isEnabled()) return false; connect(address); return true; }
    public void startInitialScan() { if (adapter == null || !adapter.isEnabled()) { callbacks.status("Bluetooth unavailable"); return; } close(); candidates.clear(); callbacks.status("Scanning for iPhone"); adapter.startLeScan(scanCallback); main.postDelayed(scanDeadline, 30000); }
    private final Runnable scanDeadline = new Runnable() { public void run() { stopScan(); callbacks.status("Scan finished"); } };
    public void stopScan() { main.removeCallbacks(scanDeadline); if (adapter != null) adapter.stopLeScan(scanCallback); }
    public void connect(String address) { stopScan(); if (adapter == null || address == null) return; close(); try { callbacks.status("Bluetooth connecting"); gatt = adapter.getRemoteDevice(address).connectGatt(context, false, callback); main.postDelayed(connectionDeadline, 30000); } catch (IllegalArgumentException e) { callbacks.status("Bluetooth address invalid"); callbacks.disconnected(); } }
    private final Runnable connectionDeadline = new Runnable() { public void run() { if (gatt != null && !authenticatedReported) { callbacks.status("Bluetooth connection timed out"); disconnect(); } } };
    public void close() { close(false); }
    private void disconnect() { close(true); }
    private void close(boolean retry) { main.removeCallbacks(connectionDeadline); stopScan(); BluetoothGatt old = gatt; gatt = null; if (queue != null) queue.clear(); queue = null; if (ancs != null) ancs.close(); if (ams != null) ams.close(); ancs = null; ams = null; rx = tx = null; if (session != null) session.close(); session = null; lines.clear(); candidates.clear(); capsSent = false; authenticatedReported = false; peerPhoneActions = false; ancsReady = amsReady = false; callbacks.cleared(); callbacks.capabilities(false, false); if (old != null) { old.disconnect(); old.close(); } if (retry) callbacks.disconnected(); }
    public void notificationAction(long uid, int action) { if (ancsReady && ancs != null) ancs.perform(uid, action); else callbacks.status("ANCS unavailable"); }
    public void mediaAction(int command) { if (amsReady && ams != null) ams.perform(command); else callbacks.status("AMS unavailable"); }
    public boolean phoneActionsAvailable() { return peerPhoneActions && session != null && session.authenticated(); }
    public boolean sendPhoneAction(String action) { if (!phoneActionsAvailable()) return false; try { writeLine(session.encrypt("phone.action", PhoneActions.payload(action))); return true; } catch (ProtocolException e) { disconnect(); callbacks.status("Phone request failed"); return false; } }
    public void sendInput(String gesture) { if (session == null || !session.peerHelloReceived()) return; try { Map<String, String> payload = new LinkedHashMap<String, String>(); payload.put("gesture", gesture); writeLine(session.encrypt("input", payload)); } catch (ProtocolException e) { disconnect(); callbacks.status("Bluetooth protocol closed"); } }
    private final BluetoothAdapter.LeScanCallback scanCallback = new BluetoothAdapter.LeScanCallback() { @Override public void onLeScan(BluetoothDevice device, int rssi, byte[] scanRecord) { if (!advertisesExplorerLink(scanRecord)) return; String address = device.getAddress(); if (!candidates.contains(address) && candidates.size() < 12) { candidates.add(address); callbacks.candidate(device.getName() == null ? "iPhone" : device.getName(), address); } } };
    private final BluetoothGattCallback callback = new BluetoothGattCallback() {
        @Override public void onConnectionStateChange(final BluetoothGatt g, final int status, final int state) { main.post(new Runnable() { @Override public void run() { if (g != gatt) return; if (status != BluetoothGatt.GATT_SUCCESS || state != BluetoothGatt.STATE_CONNECTED) { callbacks.status("Bluetooth disconnected"); disconnect(); return; } callbacks.status("Bluetooth discovering"); if (!g.discoverServices()) { callbacks.status("Bluetooth discovery failed"); disconnect(); } } }); }
        @Override public void onServicesDiscovered(final BluetoothGatt g, final int status) { main.post(new Runnable() { @Override public void run() { if (g != gatt) return; if (status != BluetoothGatt.GATT_SUCCESS) { callbacks.status("Bluetooth discovery failed"); disconnect(); return; } queue = new GattOperationQueue(new GattOperationQueue.Failure() { @Override public void onFailure() { main.post(new Runnable() { @Override public void run() { if (g != gatt) return; callbacks.status("Bluetooth operation failed"); disconnect(); } }); } }); BluetoothGattService service = g.getService(SERVICE); if (service == null || (rx = service.getCharacteristic(RX)) == null || (tx = service.getCharacteristic(TX)) == null) { callbacks.status("Explorer Link unavailable"); disconnect(); return; } try { session = new LinkSession(key); enableNotify(tx); writeLine(session.initialHello()); } catch (ProtocolException e) { callbacks.status("Bluetooth setup failed"); disconnect(); return; } ancs = g.getDevice().getBondState() != BluetoothDevice.BOND_BONDED ? null : AncsConsumer.attach(g, queue, new AncsConsumer.Callbacks() { @Override public void status(String text) { callbacks.status(text); } @Override public void notification(AncsNotifications.Notification value) { callbacks.notification(value); } @Override public void removed(long uid) { callbacks.removed(uid); } @Override public void invalidated(long uid) { callbacks.invalidated(uid); } @Override public void failure() { disconnect(); } @Override public void unavailable() { if (ancs != null) ancs.close(); ancs = null; ancsReady = false; callbacks.notificationsCleared(); publishCapabilities(); } }); ams = g.getDevice().getBondState() != BluetoothDevice.BOND_BONDED ? null : AmsRemote.attach(g, queue, new AmsRemote.Callbacks() { @Override public void status(String text) { callbacks.status(text); } @Override public void media(AmsState.Snapshot value) { callbacks.media(value); } }); if (ancs != null) { ancs.start(); if (queue != null) queue.afterPending(new Runnable() { public void run() { if (g == gatt && ancs != null) { ancsReady = true; publishCapabilities(); } } }); } if (g != gatt) return;
            if (ams != null) { ams.start(); if (queue != null) queue.afterPending(new Runnable() { public void run() { if (g == gatt && ams != null) { amsReady = true; publishCapabilities(); } } }); } if (g != gatt) return;

            BluetoothGattService generic = g.getService(GATT_SERVICE); BluetoothGattCharacteristic changed = generic == null ? null : generic.getCharacteristic(SERVICE_CHANGED);
            if (changed != null && changed.getDescriptor(CCCD) != null) enableNotify(changed); else callbacks.status("Service changes: reconnect to rediscover");
            publishCapabilities(); if (g.getDevice().getBondState() != BluetoothDevice.BOND_BONDED) callbacks.status("Pair iPhone in Bluetooth settings; reconnect"); } }); }
        @Override public void onDescriptorWrite(final BluetoothGatt g, final BluetoothGattDescriptor d, final int status) { main.post(new Runnable() { @Override public void run() { if (g == gatt && queue != null) queue.complete(status == BluetoothGatt.GATT_SUCCESS); } }); }
        @Override public void onCharacteristicWrite(final BluetoothGatt g, final BluetoothGattCharacteristic c, final int status) { main.post(new Runnable() { @Override public void run() { if (g == gatt && queue != null) { boolean rejectedAncs = ancs != null && ancs.isControl(c) && (status == 0xA2 || status == 0xA3); if (rejectedAncs) ancs.rejectedWrite(); queue.complete(status == BluetoothGatt.GATT_SUCCESS || rejectedAncs); } } }); }
        @Override public void onCharacteristicChanged(final BluetoothGatt g, final BluetoothGattCharacteristic c) { final byte[] value = c.getValue() == null ? null : c.getValue().clone(); main.post(new Runnable() { @Override public void run() { if (g != gatt) return; if (SERVICE_CHANGED.equals(c.getUuid())) { disconnect(); callbacks.status("Services changed; reconnect to rediscover"); } else if (TX.equals(c.getUuid())) receiveLink(value); else if (ancs != null && ancs.handles(c)) ancs.changed(c, value); else if (ams != null && ams.handles(c)) ams.changed(c, value); } }); }
    };
    private void enableNotify(final BluetoothGattCharacteristic characteristic) { if (gatt == null || queue == null) return; final BluetoothGattDescriptor descriptor = characteristic.getDescriptor(CCCD); if (descriptor == null) { disconnect(); callbacks.status("BLE subscription unavailable"); return; } queue.enqueue(new GattOperationQueue.Starter() { @Override public boolean start() { if (!gatt.setCharacteristicNotification(characteristic, true)) return false; descriptor.setValue(SERVICE_CHANGED.equals(characteristic.getUuid()) ? BluetoothGattDescriptor.ENABLE_INDICATION_VALUE : BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE); return gatt.writeDescriptor(descriptor); } }); }
    private void receiveLink(byte[] data) { try { if (session == null) throw new ProtocolException("Bluetooth session unavailable"); for (String line : lines.accept(data, 0, data.length)) { ProtocolMessage message = session.accept(line); if (session.peerHelloReceived() && !capsSent) { sendCapabilities(); } if (message != null) { if (!message.knownType) sendUnknownType(message.type); else if ("ping".equals(message.type)) writeLine(session.encrypt("pong", Heartbeat.pong(message))); else { if ("capabilities".equals(message.type)) peerPhoneActions = PhoneActions.advertised(message); callbacks.received(message); } if (session.authenticated()) { if (!authenticatedReported) { authenticatedReported = true; main.removeCallbacks(connectionDeadline); callbacks.authenticated(); } callbacks.status("Bluetooth authenticated"); } } } } catch (Exception e) { callbacks.status("Bluetooth protocol closed"); disconnect(); } }
    private void publishCapabilities() { callbacks.capabilities(ancsReady, amsReady); sendCapabilities(); }
    private void sendCapabilities() { if (session == null || !session.peerHelloReceived()) return; try { Map<String, String> cap = new LinkedHashMap<String, String>(); cap.put("endpoint", "glass"); cap.put("features", "ble-central,card,navigation,input" + (ancsReady ? ",ancs.available" : "") + (amsReady ? ",ams.available" : "")); writeLine(session.encrypt("capabilities", cap)); capsSent = true; } catch (ProtocolException e) { disconnect(); callbacks.status("Bluetooth protocol closed"); } }
    private void sendUnknownType(String type) throws ProtocolException { Map<String, String> payload = new LinkedHashMap<String, String>(); payload.put("code", "unknown_type"); payload.put("message", "Unsupported message type: " + printableType(type)); writeLine(session.encrypt("error", payload)); }
    private void writeLine(String line) throws ProtocolException { if (gatt == null || rx == null || queue == null) throw new ProtocolException("Bluetooth unavailable"); final byte[] data = (line + "\n").getBytes(Charset.forName("UTF-8")); for (int p = 0; p < data.length; p += 20) { final int start = p, length = Math.min(20, data.length - p); if (!queue.enqueue(new GattOperationQueue.Starter() { @Override public boolean start() { byte[] chunk = new byte[length]; System.arraycopy(data, start, chunk, 0, length); rx.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT); rx.setValue(chunk); return gatt.writeCharacteristic(rx); } })) throw new ProtocolException("Bluetooth queue full"); } }
    private static boolean advertisesExplorerLink(byte[] record) { if (record == null) return false; byte[] target = new byte[] { 0x02,0x00,0x12,(byte)0xac,0x42,0x02,0x06,(byte)0xa5,(byte)0xee,0x11,(byte)0x9e,(byte)0xb1,(byte)0xe0,(byte)0xf2,(byte)0x73,(byte)0xd9 }; for (int p = 0; p < record.length;) { int len = record[p++] & 255; if (len == 0 || p + len > record.length) return false; int type = record[p++] & 255, end = p + len - 1; if (type == 6 || type == 7) for (int q = p; q + 16 <= end; q += 16) { boolean same = true; for (int i = 0; i < 16; i++) if (record[q + i] != target[i]) { same = false; break; } if (same) return true; } p = end; } return false; }
    private static String printableType(String type) { return type.length() > 128 ? type.substring(0, 128) : type; }
}
